[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
allowRunOnSave = false
runOnSave = false
port = 8501
baseUrlPath = ""

[client]
caching = false
displayEnabled = true
showErrorDetails = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[logger]
level = "error"
